version: '3'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/uploads:/uploads
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend